apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teampass-sk-pvc
  namespace: teampass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teampass-files-pvc
  namespace: teampass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teampass-upload-pvc
  namespace: teampass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teampass-security-pvc
  namespace: teampass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teampass-db-pvc
  namespace: teampass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
