apiVersion: v1
kind: Secret
metadata:
  name: teampass-db-secret
  namespace: teampass
type: Opaque
stringData:
  mysql-root-password: "5BkDuudAYeWEJs"
  mysql-database: "teampass"
  mysql-user: "teampass"
  mysql-password: "teampass"
  admin-email: "admin@teampass.local"
  admin-pwd: "Teampass@123"
